import type { AdminDataState } from './admin-models'

const nowIso = new Date().toISOString()

export const initialAdminData: AdminDataState = {
  statuses: [
    {
      id: 1,
      name: 'Новичок',
      slug: 'newbie',
      description: 'Новый игрок клуба',
      activeImageUrl: null,
      inactiveImageUrl: null,
      perkDescription: null,
      requirements: '{}',
      isManualOnly: false,
      sortOrder: 0,
      createdAt: nowIso,
    },
    {
      id: 2,
      name: 'Резидент',
      slug: 'resident',
      description: 'Постоянный участник турниров',
      activeImageUrl: null,
      inactiveImageUrl: null,
      perkDescription: null,
      requirements: '{}',
      isManualOnly: false,
      sortOrder: 1,
      createdAt: nowIso,
    },
    {
      id: 3,
      name: 'Легенда',
      slug: 'legend',
      description: 'Подтверждается вручную админом',
      activeImageUrl: null,
      inactiveImageUrl: null,
      perkDescription: null,
      requirements: '{}',
      isManualOnly: true,
      sortOrder: 2,
      createdAt: nowIso,
    },
  ],
  achievements: [
    {
      id: 1,
      name: 'Первая победа',
      slug: 'first-win',
      description: 'Победа в турнире',
      category: null,
      iconUrl: null,
      inactiveIconUrl: null,
      sortOrder: 0,
      createdAt: nowIso,
    },
    {
      id: 2,
      name: '10 турниров',
      slug: 'ten-tournaments',
      description: 'Участие в 10 турнирах',
      category: null,
      iconUrl: null,
      inactiveIconUrl: null,
      sortOrder: 1,
      createdAt: nowIso,
    },
  ],
  series: [
    {
      id: 1,
      name: 'Февральская серия',
      startDate: '2026-02-01T00:00:00.000Z',
      endDate: '2026-02-28T23:59:59.000Z',
      isActive: true,
      createdAt: nowIso,
    },
    {
      id: 2,
      name: 'Мартовская серия',
      startDate: '2026-03-01T00:00:00.000Z',
      endDate: '2026-03-31T23:59:59.000Z',
      isActive: false,
      createdAt: nowIso,
    },
  ],
  tournaments: [
    {
      id: 1,
      seriesId: 1,
      medalId: null,
      name: 'Cascade K.O',
      description: 'Каскадный формат с баунти',
      format: 'NLH Knockout',
      imageUrl: null,
      address: 'Набережная адмиралтейского канала 27',
      locationHint: 'Вход со двора, второй этаж',
      date: '2026-03-01T19:00:00.000Z',
      maxPlayers: 100,
      prizeInfo: 'Топ 10 получают бонус к стеку',
      isSignificant: false,
      status: 'upcoming',
      createdAt: nowIso,
    },
    {
      id: 2,
      seriesId: 1,
      medalId: null,
      name: 'Freezeout Classic',
      description: 'Классический freezeout',
      format: 'NLH Freezeout',
      imageUrl: null,
      address: 'Набережная адмиралтейского канала 27',
      locationHint: 'Вход со двора, второй этаж',
      date: '2026-03-04T17:00:00.000Z',
      maxPlayers: 60,
      prizeInfo: 'Топ 5 получают бонус к стеку',
      isSignificant: false,
      status: 'upcoming',
      createdAt: nowIso,
    },
  ],
  users: [
    {
      id: 100001,
      login: 'nikita',
      telegramUsername: 'nikita_ovb',
      name: 'Никита',
      statusId: 2,
      isPrepayRequired: false,
      isOnboarded: true,
      createdAt: '2026-01-10T10:00:00.000Z',
    },
    {
      id: 100002,
      login: 'andrey',
      telegramUsername: 'andrey_ovb',
      name: 'Андрей',
      statusId: 1,
      isPrepayRequired: true,
      isOnboarded: true,
      createdAt: '2026-01-12T10:00:00.000Z',
    },
    {
      id: 100003,
      login: 'nastya',
      telegramUsername: 'nastya_ovb',
      name: 'Настя',
      statusId: 2,
      isPrepayRequired: false,
      isOnboarded: true,
      createdAt: '2026-01-18T10:00:00.000Z',
    },
    {
      id: 100004,
      login: 'georgiy',
      telegramUsername: 'georgiy_ovb',
      name: 'Георгий',
      statusId: 3,
      isPrepayRequired: false,
      isOnboarded: true,
      createdAt: '2026-01-21T10:00:00.000Z',
    },
  ],
  registrations: [
    {
      id: 1,
      userId: 100001,
      tournamentId: 1,
      registrationNumber: 1,
      status: 'registered',
      confirmedAt: '2026-02-25T10:00:00.000Z',
      cancelledAt: null,
      createdAt: '2026-02-25T10:00:00.000Z',
    },
    {
      id: 2,
      userId: 100002,
      tournamentId: 1,
      registrationNumber: 2,
      status: 'waitlist',
      confirmedAt: null,
      cancelledAt: null,
      createdAt: '2026-02-25T10:15:00.000Z',
    },
    {
      id: 3,
      userId: 100003,
      tournamentId: 1,
      registrationNumber: 3,
      status: 'registered',
      confirmedAt: null,
      cancelledAt: null,
      createdAt: '2026-02-25T10:30:00.000Z',
    },
  ],
  results: [
    {
      id: 1,
      userId: 100001,
      tournamentId: 2,
      place: 1,
      isItm: true,
      points: 120,
      bounty: 40,
      createdAt: '2026-02-20T20:00:00.000Z',
    },
    {
      id: 2,
      userId: 100003,
      tournamentId: 2,
      place: 2,
      isItm: true,
      points: 90,
      bounty: 20,
      createdAt: '2026-02-20T20:00:00.000Z',
    },
  ],
  adjustments: [
    {
      id: 1,
      userId: 100001,
      seriesId: 1,
      points: 50,
      bounty: 0,
      reason: 'Бонус за помощь',
      createdAt: '2026-02-14T10:00:00.000Z',
    },
    {
      id: 2,
      userId: 100002,
      seriesId: 1,
      points: -20,
      bounty: 0,
      reason: 'Штраф за неявку',
      createdAt: '2026-02-17T12:00:00.000Z',
    },
  ],
  userAchievements: [
    {
      id: 1,
      userId: 100001,
      achievementId: 1,
      awardedAt: '2026-02-10T12:00:00.000Z',
    },
  ],
  broadcasts: [
    {
      id: 1,
      message: 'Напоминание о турнире сегодня в 20:00',
      targetFilter: 'all',
      targetUserIds: [],
      targetSeriesId: null,
      targetTournamentId: null,
      sentCount: 4,
      status: 'sent',
      sentAt: '2026-02-27T14:00:00.000Z',
      createdAt: '2026-02-27T13:58:00.000Z',
    },
    {
      id: 2,
      message: 'Подтвердите участие и предоплату',
      targetFilter: 'registered',
      targetUserIds: [],
      targetSeriesId: null,
      targetTournamentId: 1,
      sentCount: 0,
      status: 'draft',
      sentAt: null,
      createdAt: '2026-02-28T10:20:00.000Z',
    },
  ],
}
